apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "currency-exchange-chart.fullname" . }}
  labels:
    app: {{ include "currency-exchange-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "currency-exchange-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "currency-exchange-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8000
          initialDelaySeconds: 40
          failureThreshold: 3
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8000
          initialDelaySeconds: 40
          failureThreshold: 3
          periodSeconds: 15
